### ISSUE TITLE
Adding flags is not working

### ISSUE THREAD

**Issue by bhfmts** [18F/html-proofer-docker#13]
Hi guys,

First of all, very nice job with this docker!

I am running this docker in azure. I am trying to add the flags to ignore some checkings but it is not taking the flags. It is showing me the failures anyways. For example I added the flag "--disable-external" but it is still failing :(

Here is the yml file to run the pipeline:
`trigger: none

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.4'
    addToPath: true
- script: chmod go+w $(build.sourcesDirectory)
- task: Docker@0
  displayName: 'Run Jekyll'
  inputs:
    containerRegistryType: 'Container Registry'
    action: 'Run an image'
    imageName: 'jekyll/builder:latest'
    volumes: |
      $(build.sourcesDirectory):/srv/jekyll
      $(build.binariesDirectory):/srv/jekyll/_site
    containerCommand: jekyll build --future
    detached: false
- script: docker run -v $(Build.BinariesDirectory):/site 18fgsa/html-proofer /site --empty-alt-ignore --url-ignore "/#.*/"
  displayName: Check for Broken Links
  failOnStderr: true`

**Comment by afeld** [comment]
I don't think this is a problem specific to the Docker image, as I was able to pass arguments just fine:

```
$ docker run --rm -it 18fgsa/html-proofer .
Running ["ImageCheck", "ScriptCheck", "LinkCheck"] on ["."] on *.html...


htmlproofer 3.8.0 | Error:  invalid byte sequence in UTF-8
$ docker run --rm -it 18fgsa/html-proofer . --trace
Running ["ImageCheck", "ScriptCheck", "LinkCheck"] on ["."] on *.html...


/usr/local/bundle/gems/html-proofer-3.8.0/lib/html-proofer/utils.rb:32:in `gsub': invalid byte sequence in UTF-8 (ArgumentError)
	from /usr/local/bundle/gems/html-proofer-3.8.0/lib/html-proofer/utils.rb:32:in `clean_content'
	from /usr/local/bundle/gems/html-proofer-3.8.0/lib/html-proofer/utils.rb:16:in `create_nokogiri'
	from /usr/local/bundle/gems/html-proofer-3.8.0/lib/html-proofer/runner.rb:95:in `check_path'
	from /usr/local/bundle/gems/html-proofer-3.8.0/lib/html-proofer/runner.rb:87:in `block in process_files'
	from /usr/local/bundle/gems/html-proofer-3.8.0/lib/html-proofer/runner.rb:87:in `map'
	from /usr/local/bundle/gems/html-proofer-3.8.0/lib/html-proofer/runner.rb:87:in `process_files'
	from /usr/local/bundle/gems/html-proofer-3.8.0/lib/html-proofer/runner.rb:68:in `check_files'
	from /usr/local/bundle/gems/html-proofer-3.8.0/lib/html-proofer/runner.rb:40:in `run'
	from /usr/local/bundle/gems/html-proofer-3.8.0/bin/htmlproofer:93:in `block (2 levels) in <top (required)>'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /usr/local/bundle/gems/html-proofer-3.8.0/bin/htmlproofer:9:in `<top (required)>'
	from /usr/local/bundle/bin/htmlproofer:23:in `load'
	from /usr/local/bundle/bin/htmlproofer:23:in `<main>'
```

Do those arguments work for you locally?
